import { StyleSheet } from 'react-native';
import { colors } from '../theme/colors';
import { CANVAS_W, CANVAS_H, HOTSPOT, PANEL_H } from './BaseScreen.constants';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.background },
  editToggle: {
    position: 'absolute',
    top: 8,
    right: 8,
    zIndex: 100,
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.panelBorder,
    borderRadius: 4,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  editToggleActive: { borderColor: colors.sand, backgroundColor: colors.militaryDark },
  editToggleText: { color: colors.sand, fontSize: 11, fontWeight: '700' },

  canvasScroll: { flex: 1, overflow: 'scroll' as any },
  terrain: {
    width: CANVAS_W,
    height: CANVAS_H,
    backgroundColor: '#111109',
    position: 'relative',
    overflow: 'hidden',
  },
  terrainBg: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: CANVAS_W,
    height: CANVAS_H,
  },

  hotspot: {
    position: 'absolute',
    width: HOTSPOT,
    height: HOTSPOT,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 6,
    backgroundColor: 'transparent',
  },
  hotspotSelected: {
    borderWidth: 2,
    borderColor: colors.sand,
    backgroundColor: 'rgba(200,168,75,0.15)',
  },
  hotspotEdit: {
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.25)',
    backgroundColor: 'rgba(0,0,0,0.3)',
  },
  hotspotEditTarget: {
    borderWidth: 2,
    borderColor: colors.sand,
    backgroundColor: 'rgba(200,168,75,0.2)',
  },
  glowRing: {
    position: 'absolute',
    top: -4,
    left: -4,
    right: -4,
    bottom: -4,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: colors.sandDark,
    opacity: 0.7,
  },
  levelBadge: {
    position: 'absolute',
    top: 3,
    right: 3,
    backgroundColor: colors.militaryDark,
    borderRadius: 4,
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderWidth: 1,
    borderColor: colors.military,
  },
  levelBadgeBusy: { borderColor: colors.success },
  levelBadgeText: { color: colors.textPrimary, fontSize: 9, fontWeight: '700' },
  busyDot: {
    position: 'absolute',
    top: 3,
    left: 3,
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.success,
  },
  hotspotLabelBox: {
    position: 'absolute',
    bottom: -20,
    left: '50%' as any,
    marginLeft: -90,
    width: 180,
    alignItems: 'center',
  },
  hotspotLabel: {
    backgroundColor: 'rgba(0,0,0,0.7)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
    overflow: 'hidden',
    fontSize: 10,
    color: '#FFD98E',
    fontWeight: '800',
    letterSpacing: 1.2,
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  hotspotLabelEdit: {
    color: '#00FF88',
    backgroundColor: 'rgba(0,0,0,0.85)',
  },
  hotspotLabelSelected: {
    color: '#FFFFFF',
    backgroundColor: 'rgba(196,164,85,0.5)',
    fontSize: 11,
    fontWeight: '900',
  },

  editorPanel: {
    backgroundColor: colors.surface,
    borderTopWidth: 1.5,
    borderTopColor: colors.sand,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 8,
  },
  buildingPicker: { maxHeight: 36 },
  pickerItem: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginRight: 6,
    borderWidth: 1,
    borderColor: colors.panelBorder,
    borderRadius: 4,
    backgroundColor: colors.surfaceAlt,
  },
  pickerItemActive: { borderColor: colors.sand, backgroundColor: colors.militaryDark },
  pickerText: { color: colors.textMuted, fontSize: 11, fontWeight: '600' },
  pickerTextActive: { color: colors.sand },

  coordRow: { flexDirection: 'row', gap: 16, paddingVertical: 4 },
  coordLabel: { color: colors.textSecondary, fontSize: 12 },
  coordVal: { color: colors.sand, fontWeight: '700' },

  controlRow: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  axisLabel: { color: colors.textMuted, fontSize: 11, width: 50, fontWeight: '600' },
  ctrlBtn: {
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.panelBorder,
    borderRadius: 3,
    paddingHorizontal: 8,
    paddingVertical: 5,
    minWidth: 36,
    alignItems: 'center',
  },
  ctrlBtnText: { color: colors.textPrimary, fontSize: 11, fontWeight: '700' },

  editorHint: {
    color: colors.textMuted,
    fontSize: 12,
    textAlign: 'center',
    paddingVertical: 8,
  },

  exportBtn: {
    backgroundColor: colors.militaryDark,
    borderWidth: 1,
    borderColor: colors.military,
    borderRadius: 4,
    paddingVertical: 8,
    alignItems: 'center',
  },
  exportBtnText: { color: colors.militaryLight, fontSize: 12, fontWeight: '700' },

  panel: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: PANEL_H,
    backgroundColor: colors.panel,
    borderTopWidth: 1.5,
    borderTopColor: colors.sand,
    borderTopLeftRadius: 14,
    borderTopRightRadius: 14,
    paddingHorizontal: 14,
    paddingBottom: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.5,
    shadowRadius: 12,
    elevation: 16,
  },
  panelHandle: {
    alignItems: 'center',
    paddingTop: 8,
    marginBottom: 6,
    justifyContent: 'center',
  },
  handleBar: { width: 36, height: 4, borderRadius: 2, backgroundColor: colors.panelBorder },
  closeBtn: { position: 'absolute', right: 4, top: 2, padding: 12, zIndex: 20 },
  closeBtnText: { color: '#ffffff', fontSize: 22, fontWeight: '900' as const },
  panelHeader: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 10 },
  panelTitleBlock: { flex: 1 },
  panelName: { color: colors.textPrimary, fontSize: 16, fontWeight: '700' },
  panelLevel: { color: colors.sand, fontSize: 12 },
  tabRow: { flexDirection: 'row', gap: 4, marginBottom: 8 },
  tabBtn: {
    flex: 1,
    paddingVertical: 6,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.panelBorder,
    borderRadius: 3,
  },
  tabBtnActive: { borderColor: colors.sand, backgroundColor: colors.surfaceAlt },
  tabBtnText: { color: colors.textMuted, fontSize: 11, fontWeight: '600' },
  tabBtnTextActive: { color: colors.sand },
  tabContent: { flex: 1 },

  overviewContent: { gap: 8 },
  prodInfoRow: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingVertical: 4, borderWidth: 1, borderColor: colors.panelBorder, borderRadius: 4, paddingHorizontal: 8, backgroundColor: colors.surfaceAlt },
  prodLabel: { color: colors.textMuted, fontSize: 11 },
  prodCurrent: { color: colors.sand, fontSize: 12, fontWeight: '700' },
  prodNext: { color: colors.military, fontSize: 11 },
  costRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginBottom: 6 },
  costChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.panelBorder,
    borderRadius: 3,
    paddingHorizontal: 7,
    paddingVertical: 3,
  },
  costChipIcon: { fontSize: 11 },
  costChipVal: { color: colors.textPrimary, fontSize: 11, fontWeight: '600' },
  blockRow: {
    backgroundColor: 'rgba(200,80,80,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(200,80,80,0.3)',
    borderRadius: 4,
    padding: 8,
    marginBottom: 6,
  },
  blockText: {
    color: colors.danger,
    fontSize: 12,
    lineHeight: 16,
  },
  nextLevelBox: {
    marginTop: 10,
    padding: 10,
    backgroundColor: 'rgba(210,180,100,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(210,180,100,0.25)',
    borderRadius: 6,
    gap: 6,
  },
  nextLevelTitle: {
    color: colors.sand,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  nextLevelTitleFar: { color: colors.textMuted },
  nextLevelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  nextLevelThumb: { width: 36, height: 36, borderRadius: 4 },
  nextLevelIcon: { fontSize: 14 },
  nextLevelText: { color: colors.textSecondary, fontSize: 12, flex: 1 },
  nextLevelBadge: {
    color: colors.sand,
    fontSize: 9,
    fontWeight: '900',
    borderWidth: 1,
    borderColor: colors.sand,
    borderRadius: 3,
    paddingHorizontal: 4,
    paddingVertical: 1,
  },
  nextLevelBadgeFar: {
    color: colors.textMuted,
    fontSize: 9,
    fontWeight: '700',
    borderWidth: 1,
    borderColor: colors.textMuted,
    borderRadius: 3,
    paddingHorizontal: 4,
    paddingVertical: 1,
  },
  trainedSection: {
    borderTopWidth: 1,
    borderTopColor: colors.panelBorder,
    paddingTop: 8,
    gap: 4,
  },
  sectionLabel: { color: colors.textMuted, fontSize: 9, letterSpacing: 1.5, marginBottom: 4 },
  trainedRow: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingVertical: 2 },
  trainedThumb: { width: 32, height: 32, borderRadius: 4 },
  trainedIcon: { fontSize: 14, width: 20 },
  trainedId: { color: colors.textSecondary, fontSize: 12, flex: 1 },
  trainedCount: { color: colors.sand, fontSize: 12, fontWeight: '700' },
  emptyText: { color: colors.textMuted, fontSize: 12, textAlign: 'center', paddingVertical: 12 },

  unitCard: {
    borderWidth: 1,
    borderColor: colors.panelBorder,
    borderRadius: 4,
    padding: 8,
    marginBottom: 6,
    backgroundColor: colors.surface,
  },
  unitCardSelected: { borderColor: colors.sand },
  unitCardRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  unitCardIcon: { fontSize: 24 },
  unitCardBanner: {
    width: '100%',
    height: 120,
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
    backgroundColor: colors.surfaceAlt,
  },
  unitCardThumb: {
    width: 72,
    height: 50,
    borderRadius: 3,
    backgroundColor: colors.surfaceAlt,
  },
  unitCardInfo: { flex: 1 },
  unitCardName: { color: colors.textPrimary, fontSize: 13, fontWeight: '700' },
  unitCardStat: { color: colors.textSecondary, fontSize: 10, marginTop: 1 },
  unitCardTrained: { color: colors.military, fontSize: 10 },
  costSmall: { color: colors.textMuted, fontSize: 10 },
  trainControls: {
    marginTop: 8,
    borderTopWidth: 1,
    borderTopColor: colors.panelBorder,
    paddingTop: 8,
    gap: 6,
  },
  stepperRow: { flexDirection: 'row', alignItems: 'center', gap: 4, flexWrap: 'wrap', justifyContent: 'center' },
  stepBtn: {
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.panelBorder,
    borderRadius: 3,
    paddingHorizontal: 7,
    paddingVertical: 5,
  },
  stepBtnText: { color: colors.textPrimary, fontSize: 12, fontWeight: '700' },
  stepperInput: {
    color: colors.sand,
    fontSize: 16,
    fontWeight: '700',
    minWidth: 50,
    textAlign: 'center',
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.sand,
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingVertical: 4,
  },
  trainCostText: { color: colors.textSecondary, fontSize: 11 },

  researchCard: {
    borderWidth: 1,
    borderColor: colors.panelBorder,
    borderRadius: 4,
    padding: 8,
    marginBottom: 6,
    backgroundColor: colors.surface,
    gap: 4,
  },
  researchCardSelected: { borderColor: colors.sand },
  researchName: { color: colors.textPrimary, fontSize: 13, fontWeight: '700' },
  researchDesc: { color: colors.textSecondary, fontSize: 11, lineHeight: 16 },

  harekatContent: { gap: 8 },

  hqMarchBox: {
    padding: 10, borderWidth: 1, borderColor: colors.sand,
    borderRadius: 4, backgroundColor: 'rgba(200,168,75,0.08)', gap: 4,
  },
  hqMarchTitle: { color: colors.sand, fontSize: 11, fontWeight: '700', letterSpacing: 1 },
  hqMarchTarget: { color: colors.textPrimary, fontSize: 13, fontWeight: '700' },
  hqMarchSub: { color: colors.textSecondary, fontSize: 11 },

  hqArmyBox: {
    padding: 10, borderWidth: 1, borderColor: colors.panelBorder,
    borderRadius: 4, backgroundColor: colors.surface, gap: 6,
  },
  hqArmyRow: { flexDirection: 'row', justifyContent: 'space-between' },
  hqArmyTotal: { color: colors.textPrimary, fontSize: 13, fontWeight: '700' },
  hqArmyPower: { color: colors.sand, fontSize: 12, fontWeight: '700' },
  hqBreakdownRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  hqChip: {
    flexDirection: 'row', alignItems: 'center', gap: 3,
    backgroundColor: colors.surfaceAlt, borderWidth: 1, borderColor: colors.panelBorder,
    borderRadius: 3, paddingHorizontal: 7, paddingVertical: 3,
  },
  hqChipIcon: { fontSize: 11 },
  hqChipLabel: { color: colors.textSecondary, fontSize: 10 },
  hqChipCount: { color: colors.sand, fontSize: 10, fontWeight: '700' },

  hqStepperBox: {
    padding: 10, borderWidth: 1, borderColor: colors.panelBorder,
    borderRadius: 4, backgroundColor: colors.surface, gap: 6,
  },
  hqStepperLabel: { color: colors.textSecondary, fontSize: 11 },
  hqStepperRow: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  hqStepBtn: {
    backgroundColor: colors.surfaceAlt, borderWidth: 1, borderColor: colors.panelBorder,
    borderRadius: 3, paddingHorizontal: 9, paddingVertical: 5,
  },
  hqStepBtnText: { color: colors.textPrimary, fontSize: 12, fontWeight: '700' },
  hqStepVal: {
    color: colors.sand, fontSize: 16, fontWeight: '700',
    minWidth: 44, textAlign: 'center', fontVariant: ['tabular-nums'],
  },

  hqTargetSectionLabel: {
    color: colors.textMuted, fontSize: 9, letterSpacing: 1.5, marginTop: 4,
  },
  hqTargetCard: {
    borderWidth: 1, borderColor: colors.panelBorder, borderRadius: 3,
    padding: 8, marginTop: 4, backgroundColor: colors.surface,
  },
  hqTargetCardSel: { borderColor: colors.sand },
  hqTargetHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 2 },
  hqTargetName: { color: colors.textPrimary, fontSize: 13, fontWeight: '700' },
  hqDiffBadge: { paddingHorizontal: 5, paddingVertical: 2, borderRadius: 2 },
  hqDiffText: { fontSize: 9, fontWeight: '700', letterSpacing: 1 },
  hqTargetPlayer: { color: colors.textSecondary, fontSize: 10, marginBottom: 4 },
  hqTargetStats: { flexDirection: 'row', gap: 10, marginBottom: 4, alignItems: 'center' },
  hqTargetStat: { color: colors.textSecondary, fontSize: 10 },
  hqWinChance: { fontSize: 10, fontWeight: '700', marginLeft: 'auto' },
  hqTargetRewards: { flexDirection: 'row', gap: 8 },
  hqRewardText: { color: colors.textPrimary, fontSize: 11, fontWeight: '600' },

  hqLogBox: { gap: 4, marginTop: 4 },
  hqLogRow: {
    flexDirection: 'row', alignItems: 'center', gap: 7,
    paddingVertical: 5, borderBottomWidth: 1, borderBottomColor: colors.panelBorder,
  },
  hqLogWon: { color: '#4caf50', fontSize: 14 },
  hqLogLost: { color: '#f44336', fontSize: 14 },
  hqLogName: { color: colors.textPrimary, fontSize: 11, fontWeight: '600' },
  hqLogTime: { color: colors.textMuted, fontSize: 10 },
  hqLogGain: { color: '#4caf50', fontSize: 10, fontWeight: '700' },
  hqLogLossText: { color: '#FF5252', fontSize: 10, fontWeight: '700' },

  birlikSection: { gap: 6 },
  birlikHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  birlikCreateBtn: {
    backgroundColor: colors.militaryDark, borderWidth: 1, borderColor: colors.military,
    borderRadius: 3, paddingHorizontal: 10, paddingVertical: 5,
  },
  birlikCreateBtnText: { color: colors.militaryLight, fontSize: 11, fontWeight: '700' },
  birlikCard: {
    borderWidth: 1, borderColor: colors.panelBorder, borderRadius: 4,
    padding: 8, backgroundColor: colors.surface,
  },
  birlikCardSel: { borderColor: colors.sand, backgroundColor: 'rgba(200,168,75,0.06)' },
  birlikCardRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  birlikName: { color: colors.textPrimary, fontSize: 12, fontWeight: '700' },
  birlikSlotRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 3, flexWrap: 'wrap' },
  birlikSlotChip: { color: colors.textSecondary, fontSize: 12 },
  birlikTotal: { color: colors.sand, fontSize: 11, fontWeight: '700', marginLeft: 4 },
  birlikSelBtn: {
    borderWidth: 1, borderColor: colors.panelBorder, borderRadius: 3,
    paddingHorizontal: 10, paddingVertical: 5,
  },
  birlikSelBtnActive: { borderColor: colors.sand, backgroundColor: colors.militaryDark },
  birlikSelBtnText: { color: colors.textMuted, fontSize: 11, fontWeight: '700' },
  birlikSelBtnTextActive: { color: colors.sand },
  birlikDelBtn: { padding: 6 },
  birlikDelBtnText: { fontSize: 14 },

  birlikForm: {
    borderWidth: 1, borderColor: colors.sand, borderRadius: 6,
    padding: 10, backgroundColor: 'rgba(200,168,75,0.05)', gap: 8,
  },
  birlikFormTitle: { color: colors.sand, fontSize: 12, fontWeight: '700', letterSpacing: 1 },
  birlikNameInput: {
    borderWidth: 1, borderColor: colors.panelBorder, borderRadius: 4,
    backgroundColor: colors.surfaceAlt, color: colors.textPrimary,
    fontSize: 13, paddingHorizontal: 10, paddingVertical: 6,
  },
  birlikFormRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  birlikFormIcon: { fontSize: 16, width: 22 },
  birlikFormThumb: { width: 28, height: 28, borderRadius: 4, marginRight: 4 },
  birlikFormLabel: { color: colors.textSecondary, fontSize: 12, flex: 1 },
  birlikFormAvail: { color: colors.textMuted, fontSize: 10 },
  birlikFormBtn: {
    backgroundColor: colors.surfaceAlt, borderWidth: 1, borderColor: colors.panelBorder,
    borderRadius: 3, paddingHorizontal: 9, paddingVertical: 4,
  },
  birlikFormBtnText: { color: colors.textPrimary, fontSize: 13, fontWeight: '700' },
  birlikFormCount: { color: colors.sand, fontSize: 15, fontWeight: '700', minWidth: 28, textAlign: 'center' },
  birlikFormActions: { flexDirection: 'row', gap: 8, marginTop: 4 },
  birlikCancelBtn: {
    flex: 1, borderWidth: 1, borderColor: colors.panelBorder, borderRadius: 4,
    paddingVertical: 8, alignItems: 'center',
  },
  birlikCancelBtnText: { color: colors.textMuted, fontSize: 12, fontWeight: '600' },
  birlikSaveBtn: {
    flex: 2, borderWidth: 1, borderColor: colors.military, borderRadius: 4,
    paddingVertical: 8, alignItems: 'center', backgroundColor: colors.militaryDark,
  },
  birlikSaveBtnDisabled: { opacity: 0.4 },
  birlikSaveBtnText: { color: colors.militaryLight, fontSize: 12, fontWeight: '700' },
  researchBranchRow: {
    flexDirection: 'row',
    marginBottom: 8,
    gap: 4,
  },
  researchBranchBtn: {
    flex: 1,
    paddingVertical: 6,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: colors.panelBorder,
    alignItems: 'center',
  },
  researchBranchBtnActive: {
    backgroundColor: colors.military,
    borderColor: colors.military,
  },
  researchBranchLabel: {
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: '600',
  },
  researchBranchLabelActive: {
    color: '#fff',
  },

  birlikModalOverlay: {
    flex: 1, backgroundColor: colors.overlay,
    justifyContent: 'center', alignItems: 'center', padding: 16,
  },
  birlikModalPanel: {
    backgroundColor: colors.panel, borderWidth: 1, borderColor: colors.sand,
    borderRadius: 6, padding: 16, width: '100%', maxHeight: '85%', gap: 10,
  },
  birlikModalHeader: {
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
  },
  birlikModalTitle: { color: colors.sand, fontSize: 18, fontWeight: '900', letterSpacing: 2 },
  birlikModalClose: { padding: 4 },
  birlikModalCloseText: { color: colors.textSecondary, fontSize: 18 },
  birlikModalSelectHeader: {
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
  },
  birlikModalSelectLabel: { color: colors.textPrimary, fontSize: 13, fontWeight: '700' },
  birlikModalSelectAll: { color: colors.sand, fontSize: 12, fontWeight: '700' },
  birlikModalList: { maxHeight: 340 },
  birlikModalBranchHeader: {
    flexDirection: 'row', alignItems: 'center', gap: 6,
    paddingVertical: 6, marginTop: 4,
    borderBottomWidth: 1, borderBottomColor: colors.sand + '33',
  },
  birlikModalBranchIcon: { fontSize: 14 },
  birlikModalBranchLabel: { color: colors.sand, fontSize: 12, fontWeight: '800', letterSpacing: 1 },
  birlikModalNoUnits: { alignItems: 'center', paddingVertical: 20, gap: 6 },
  birlikModalNoUnitsIcon: { fontSize: 32 },
  birlikModalNoUnitsTitle: { color: colors.sand, fontSize: 16, fontWeight: '700' },
  birlikModalNoUnitsDesc: { color: colors.textSecondary, fontSize: 12, textAlign: 'center' },
  birlikModalUnitRow: {
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
    paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: colors.panelBorder,
  },
  birlikModalUnitInfo: { flexDirection: 'row', alignItems: 'center', gap: 8, flex: 1 },
  birlikModalUnitImg: { width: 40, height: 28, borderRadius: 3 },
  birlikModalUnitName: { color: colors.textPrimary, fontSize: 12, fontWeight: '600' },
  birlikModalUnitAvail: { color: colors.textMuted, fontSize: 10 },
  birlikModalStepper: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  birlikModalStepBtn: {
    backgroundColor: colors.surfaceAlt, borderWidth: 1, borderColor: colors.panelBorder,
    borderRadius: 3, paddingHorizontal: 8, paddingVertical: 4,
  },
  birlikModalStepBtnText: { color: colors.textPrimary, fontSize: 11, fontWeight: '700' },
  birlikModalStepVal: { color: colors.sand, fontSize: 13, fontWeight: '700', minWidth: 28, textAlign: 'center' },
  birlikModalStepInput: { color: colors.sand, fontSize: 13, fontWeight: '700', minWidth: 42, textAlign: 'center', backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.panelBorder, borderRadius: 4, paddingVertical: 2, paddingHorizontal: 4 },
  birlikModalSummary: {
    backgroundColor: colors.surfaceAlt, borderRadius: 3, padding: 8,
    borderWidth: 1, borderColor: colors.panelBorder,
  },
  birlikModalSummaryText: { color: colors.textSecondary, fontSize: 12 },
});
